"""header

Revision ID: 21417bdc66cb
Revises: 702308b23ca
Create Date: 2017-05-04 19:21:24.362000

"""

# revision identifiers, used by Alembic.
revision = '21417bdc66cb'
down_revision = '702308b23ca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('header_url', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'header_url')
    ### end Alembic commands ###
