"""add title

Revision ID: 2d06f01737c2
Revises: 51f5ccfba190
Create Date: 2017-04-23 16:04:00.912000

"""

# revision identifiers, used by Alembic.
revision = '2d06f01737c2'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    ### end Alembic commands ###
