"""add category

Revision ID: 2f1a00b10f2a
Revises: 2d06f01737c2
Create Date: 2017-04-26 12:52:53.676000

"""

# revision identifiers, used by Alembic.
revision = '2f1a00b10f2a'
down_revision = '2d06f01737c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registrations',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['categories.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registrations')
    op.drop_table('categories')
    ### end Alembic commands ###
