"""add timestamp

Revision ID: 702308b23ca
Revises: 2f1a00b10f2a
Create Date: 2017-04-26 16:43:31.491000

"""

# revision identifiers, used by Alembic.
revision = '702308b23ca'
down_revision = '2f1a00b10f2a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index('ix_categories_timestamp', 'categories', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_categories_timestamp', 'categories')
    op.drop_column('categories', 'timestamp')
    ### end Alembic commands ###
